//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type JudgeEventRel struct {
	JudgeID int32  `sql:"primary_key"`
	EventID string `sql:"primary_key"`
}
