//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type StudentStudentGroupRel struct {
	StudentGroupID int32  `sql:"primary_key"`
	StudentEmail   string `sql:"primary_key"`
}
