//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Judge = newJudgeTable("", "judge", "")

type judgeTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Name sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type JudgeTable struct {
	judgeTable

	EXCLUDED judgeTable
}

// AS creates new JudgeTable with assigned alias
func (a JudgeTable) AS(alias string) *JudgeTable {
	return newJudgeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new JudgeTable with assigned schema name
func (a JudgeTable) FromSchema(schemaName string) *JudgeTable {
	return newJudgeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new JudgeTable with assigned table prefix
func (a JudgeTable) WithPrefix(prefix string) *JudgeTable {
	return newJudgeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new JudgeTable with assigned table suffix
func (a JudgeTable) WithSuffix(suffix string) *JudgeTable {
	return newJudgeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newJudgeTable(schemaName, tableName, alias string) *JudgeTable {
	return &JudgeTable{
		judgeTable: newJudgeTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newJudgeTableImpl("", "excluded", ""),
	}
}

func newJudgeTableImpl(schemaName, tableName, alias string) judgeTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{NameColumn}
	)

	return judgeTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
