//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Config = Config.FromSchema(schema)
	Event = Event.FromSchema(schema)
	Judge = Judge.FromSchema(schema)
	JudgeEventRel = JudgeEventRel.FromSchema(schema)
	Room = Room.FromSchema(schema)
	Student = Student.FromSchema(schema)
	StudentGroup = StudentGroup.FromSchema(schema)
	StudentStudentGroupRel = StudentStudentGroupRel.FromSchema(schema)
	TimeSlot = TimeSlot.FromSchema(schema)
}
