//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TimeSlot = newTimeSlotTable("", "time_slot", "")

type timeSlotTable struct {
	sqlite.Table

	// Columns
	ID       sqlite.ColumnInteger
	ConfigID sqlite.ColumnInteger
	Duration sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type TimeSlotTable struct {
	timeSlotTable

	EXCLUDED timeSlotTable
}

// AS creates new TimeSlotTable with assigned alias
func (a TimeSlotTable) AS(alias string) *TimeSlotTable {
	return newTimeSlotTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TimeSlotTable with assigned schema name
func (a TimeSlotTable) FromSchema(schemaName string) *TimeSlotTable {
	return newTimeSlotTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TimeSlotTable with assigned table prefix
func (a TimeSlotTable) WithPrefix(prefix string) *TimeSlotTable {
	return newTimeSlotTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TimeSlotTable with assigned table suffix
func (a TimeSlotTable) WithSuffix(suffix string) *TimeSlotTable {
	return newTimeSlotTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTimeSlotTable(schemaName, tableName, alias string) *TimeSlotTable {
	return &TimeSlotTable{
		timeSlotTable: newTimeSlotTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newTimeSlotTableImpl("", "excluded", ""),
	}
}

func newTimeSlotTableImpl(schemaName, tableName, alias string) timeSlotTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		ConfigIDColumn = sqlite.IntegerColumn("config_id")
		DurationColumn = sqlite.IntegerColumn("duration")
		allColumns     = sqlite.ColumnList{IDColumn, ConfigIDColumn, DurationColumn}
		mutableColumns = sqlite.ColumnList{ConfigIDColumn, DurationColumn}
	)

	return timeSlotTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		ConfigID: ConfigIDColumn,
		Duration: DurationColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
